// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are configured only for Android. '
      'This application is intended for Android builds.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfhCEHI2Pl7LhlDw0TQuLe-M08zZz_f3I',
    appId: '1:653018830489:android:0b5a8e5e5c4de7e3290a08',
    messagingSenderId: '653018830489',
    projectId: 'lahoredulhasuiting-87108',
    databaseURL: 'https://lahoredulhasuiting-87108-default-rtdb.firebaseio.com',
    storageBucket: 'lahoredulhasuiting-87108.firebasestorage.app',
  );
}