// File generated by flutterfire configure
// File generated on 2024-12-19 12:00:00.000000

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdyJT3lyS9lNwJNUZAj1I-mT5NKTVGjAY',
    appId: '1:61258568836:android:e0bb902a071fd43cee1ed1',
    messagingSenderId: '61258568836',
    projectId: 'tailorx-jaat001',
    storageBucket: 'tailorx-jaat001.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXFxaKZFQelRqxltDiYvTFJm1itFRFW_E',
    appId: '1:61258568836:web:8f9fcf5d4ae33216ee1ed1',
    messagingSenderId: '61258568836',
    projectId: 'tailorx-jaat001',
    authDomain: 'tailorx-jaat001.firebaseapp.com',
    storageBucket: 'tailorx-jaat001.firebasestorage.app',
    measurementId: 'G-ZQTGTXE264',
  );

}